# 이해/코드 작성 보조를 위한 주피터 노트북

## LRW npz 구조 이해

In [8]:
import numpy as np
from PIL import Image


save_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/'
visual_data_path = f'{save_path}/datasets/visual_data/AFTERNOON/test/AFTERNOON_00001.npz'
landmarks_path = f'{save_path}/landmarks/LRW_landmarks/AFTERNOON/test/AFTERNOON_00001.npz'

npz = np.load(visual_data_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    print(f'@#$#@$ npy.shape: {npy.shape}')
    print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    print(f'@#$#@$ npy.shape 1: {npy.shape[1]}')
    # image = Image.fromarray(npy)
    # image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/AFTERNOON/vis_AFTERNOON_00001_{i}.png')
    print(f'\n ------- vis 저장 완료 ------- \n')
    break

npz = np.load(landmarks_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    print(f'@#$#@$ npy.keys: {npy[0].keys()}')
    print(f'@#$#@$ npy.values: {npy[0].values()}')
    print(f'@#$#@$ npy.shape: {npy.shape}')
    print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    # image = Image.fromarray(npy)
    # image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/AFTERNOON/land_AFTERNOON_00001_{i}.png')
    print(f'\n ------- land 저장 완료 ------- \n')
    break


 ------- 0 번째 npy: [[116 115 114 ... 102 103 109]
 [115 114 113 ... 102 102 107]
 [114 113 113 ... 102 101 104]
 ...
 [101 117 103 ... 120 129 134]
 [110 108 105 ... 126 123 131]
 [119  96 108 ... 125 120 130]] -------
@#$#@$ npy.shape: (96, 96)
@#$#@$ npy.shape 0: 96
@#$#@$ npy.shape 1: 96

 ------- vis 저장 완료 ------- 


 ------- 0 번째 npy: [{'id': 15785, 'most_recent_fitting_scores': array([2.1393867, 2.2493362, 1.9258147], dtype=float32), 'facial_landmarks': array([[ 69.079834,  97.41166 ],
        [ 68.593735, 113.192764],
        [ 68.93317 , 129.05174 ],
        [ 69.98113 , 145.5383  ],
        [ 74.01223 , 161.29114 ],
        [ 82.7931  , 174.80899 ],
        [ 94.87536 , 186.33684 ],
        [109.80077 , 195.82143 ],
        [127.097626, 199.09102 ],
        [144.41997 , 197.57303 ],
        [159.29811 , 189.94516 ],
        [171.63803 , 179.6567  ],
        [180.63264 , 166.58208 ],
        [185.93953 , 151.43419 ],
        [188.94734 , 135.95068 ],
        [190.98651 , 120.4

In [91]:
import numpy as np
from PIL import Image


save_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/'
visual_data_path = f'{save_path}/datasets/visual_data/특히/train/특히_00001.npz'
landmarks_path = f'{save_path}/landmarks/hangeul_landmarks/특히/train/특히_00001.npz'

npz = np.load(visual_data_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    # print(f'@#$#@$ npy.shape: {npy.shape}')
    # print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    # print(f'@#$#@$ npy.shape 1: {npy.shape[1]}')
    image = Image.fromarray(npy)
    image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/특히/vis_00001_{i}.png')
    print(f'\n ------- vis 저장 완료 ------- \n')

npz = np.load(landmarks_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    print(f'@#$#@$ npy.keys: {npy[0].keys()}')
    print(f'@#$#@$ npy.values: {npy[0].values()}')
    print(f'@#$#@$ npy.shape: {npy.shape}')
    print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    # image = Image.fromarray(npy)
    # image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/특히/land_00001_{i}.png')
    print(f'\n ------- land 저장 완료 ------- \n')
    break


 ------- 0 번째 npy: [[159 159 159 ... 173 173 173]
 [159 159 159 ... 173 173 173]
 [159 159 159 ... 165 163 161]
 ...
 [155 133 129 ... 202 228 188]
 [165 146 138 ... 202 229 195]
 [172 156 145 ... 200 207 151]] -------

 ------- vis 저장 완료 ------- 


 ------- 1 번째 npy: [[159 159 159 ... 173 173 173]
 [159 159 159 ... 173 173 173]
 [159 159 159 ... 173 173 173]
 ...
 [151 133 129 ... 202 231 187]
 [160 145 138 ... 202 223 179]
 [168 155 145 ... 201 195 131]] -------

 ------- vis 저장 완료 ------- 


 ------- 2 번째 npy: [[167 162 155 ... 173 173 173]
 [176 171 164 ... 173 173 173]
 [177 172 164 ... 173 173 173]
 ...
 [148 125 121 ... 202 231 187]
 [157 136 126 ... 202 223 179]
 [166 148 133 ... 201 195 131]] -------

 ------- vis 저장 완료 ------- 


 ------- 3 번째 npy: [[165 160 152 ... 163 163 165]
 [166 161 153 ... 173 173 173]
 [171 168 161 ... 173 173 173]
 ...
 [148 125 121 ... 202 231 187]
 [157 136 126 ... 202 223 179]
 [166 148 133 ... 201 195 131]] -------

 ------- vis 저장 완료 ------- 



## multi_sub_landmarks 구조 이해

In [14]:
import numpy as np
from utils import *  # utils.py 모듈에 있는 모든 함수 불러오기


# person_id = 0

# landmarks = [None] * 5
# facial_landmarks = {'facial_landmarks': landmarks}
# person_landmarks = [facial_landmarks] * 5
# multi_sub_landmarks = [person_landmarks] * 5

# landmarks_2 = [None] * len( multi_sub_landmarks)

# print('\n @@@@@ facial_landmarks: ', facial_landmarks)
# print('\n @@@@@ person_landmarks: ', person_landmarks)
# print('\n @@@@@ multi_sub_landmarks: ', multi_sub_landmarks)
# print()
# print('\n @@@@@ landmarks_2: ', landmarks_2)

# for frame_idx in range(len(multi_sub_landmarks)):
#     landmarks_2[frame_idx] = multi_sub_landmarks[frame_idx][person_id]['facial_landmarks']
#     print('\n ###########', frame_idx, landmarks_2[frame_idx])
#     break

###################################

# npz = np.array(multi_sub_landmarks)
SAVE_PATH = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/test/test.npz'
# save2npz(SAVE_PATH,data=npz)

###################################

person_id = 0
multi_sub_landmarks = np.load(SAVE_PATH, allow_pickle=True)['data']
landmarks = [None] * len( multi_sub_landmarks)
for frame_idx in range(len(landmarks)):
    landmarks[frame_idx] = multi_sub_landmarks[frame_idx][int(person_id)]['facial_landmarks']
    print('@@@@@ landmarks[frame_idx]: ', landmarks[frame_idx])
    break
    

@@@@@ landmarks[frame_idx]:  [None, None, None, None, None]


## 프레임 맞추기 코드 이해

In [24]:
import numpy as np

target = 29
n_frames = 53

x = np.linspace(1,2,10)  # 구간 시작점, 구간 끝점, 구간 내 숫자 개수
print('\n\n ### x: ', x)

idx = np.linspace(0,n_frames-1,29)
print('\n\n ### idx: ', idx)
print('\n ### len(idx): ', len(idx))
print('\n ### type(idx): ', type(idx))

idx = np.around(idx, 0).astype(np.int32)
print('\n\n ###### idx: ', idx)
print('\n ###### len(idx): ', len(idx))
print('\n ###### type(idx): ', type(idx))

print('\n ################################### \n')

target = 29
n_frames = 10

video_shape = (1080,1920,29)
output_video = np.zeros(video_shape).astype(np.uint8)
print('\n\n ### zero_padding: ', output_video)
print('\n ### len(zero_padding): ', len(output_video))
print('\n ### type(zero_padding): ', type(output_video))

# VIDEO_PATH = ''
# video = cv2.?
# output_video[:, :, :n_frames] = video
# for i in range(target-n_frames+1):
#     output_video[:, :, i+n_frames-1] = output_video[:, :, n_frames-1]
#     print(f'\n\n ###### {i}번째 output_video[:, :, n_frames-1]', output_video[:, :, n_frames-1])
#     print(f'\n ###### {i}번째 output_video[:, :, i+n_frames-1]', output_video[:, :, i+n_frames-1])



 ### x:  [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


 ### idx:  [ 0.          1.85714286  3.71428571  5.57142857  7.42857143  9.28571429
 11.14285714 13.         14.85714286 16.71428571 18.57142857 20.42857143
 22.28571429 24.14285714 26.         27.85714286 29.71428571 31.57142857
 33.42857143 35.28571429 37.14285714 39.         40.85714286 42.71428571
 44.57142857 46.42857143 48.28571429 50.14285714 52.        ]

 ### len(idx):  29

 ### type(idx):  <class 'numpy.ndarray'>


 ###### idx:  [ 0  2  4  6  7  9 11 13 15 17 19 20 22 24 26 28 30 32 33 35 37 39 41 43
 45 46 48 50 52]

 ###### len(idx):  29

 ###### type(idx):  <class 'numpy.ndarray'>

 ################################### 



 ### zero_padding:  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 

ValueError: could not broadcast input array from shape (3,) into shape (1080,1920,10)

## korean_detected_face.csv 작성, avi 파일명 변경, 영상 align txt 작성

In [77]:
import os
import re


word_list = ['특히', '하지만', '그리고', '이렇게', '함께', '어떤', '이번', '오늘', '다른', '코로나', '확진자', '뉴스에서', '미국', '한국', '한국어']
word_dict = {
    'especially': '특히',
    'but': '하지만',
    'and': '그리고',
    'eruke': '이렇게',
    'with': '함께',
    'othun': '어떤',
    'this': '이번',
    'today': '오늘',
    'differ': '다른',
    'covid': '코로나',
    'huak': '확진자',
    'atnews': '뉴스에서',
    'usa': '미국',
    'korea': '한국',
    'korean': '한국어'
}
dir_list = ['train', 'val', 'test']
data_dir = '/home/PHR/Lipreading_using_TCN_running/hangeul'

# for word in word_list:
#     for dir in dir_list:
#         dir_path = f'{data_dir}/{word}/{dir}' 
#         if not os.path.exists(dir_path):                      
#             os.makedirs(dir_path)  # 디렉토리 생성
#             print(f'{word}/{dir} 폴더 생성')


csv_path = f'{data_dir}/korean_detected_face.csv'
f = open(csv_path, 'w')


for word in word_list:
    for dir in dir_list:
        dir_path = f'{data_dir}/{word}/{dir}'
        nums_list = []
        for file in os.listdir(dir_path):
            if file.endswith('.avi'):
                # --- avi 파일명 변경 ---
                file_oldname = f'{dir_path}/{file}'
                file_name, nums_ext = file.split('_')
                nums, ext = nums_ext.split('.')
                nums = nums.zfill(5)
                nums_list.append(nums)

                if not re.compile('[가-힣]+').findall(file_name):
                    file_newname = word_dict[file_name]
                file_newname = f'{dir_path}/{file_name}_{nums}'
                video_filename = f'{file_newname}.{ext}'
                os.rename(file_oldname, video_filename)

                # --- txt 파일 생성 ---
                txt_filename = f'{file_newname}.txt'
                txt_contents = 'Disk reference: 1\nChannel: Sejong\nProgram start: 2022-05-30 18:40:00 +0000\nClip start: 63.3 seconds\nDuration: 1.2 seconds'

                with open(txt_filename, 'w') as txt_file:
                    txt_file.write(txt_contents)

        nums_list.sort()
        for nums in nums_list:
            # --- CSV 작성 ---
            csv_str = f'{file_name}/{dir}/{file_name}_{nums},0\n'
            f.writelines(csv_str)



f.close()


## TEST

In [65]:
a = [(0,0)]
a

[(0, 0)]

In [67]:
b = a * 68
b[36:48]

[(0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0)]

## 구축한 한국어 데이터셋 확인

In [81]:
import os
import re

# import plotly.plotly as py


word_list = ['특히', '하지만', '그리고', '이렇게', '함께', '어떤', '이번', '오늘', '다른', '코로나', '확진자', '뉴스에서', '미국', '한국', '한국어']
word_dict = {
    'especially': '특히',
    'but': '하지만',
    'and': '그리고',
    'eruke': '이렇게',
    'with': '함께',
    'othun': '어떤',
    'this': '이번',
    'today': '오늘',
    'differ': '다른',
    'covid': '코로나',
    'huak': '확진자',
    'atnews': '뉴스에서',
    'usa': '미국',
    'korea': '한국',
    'korean': '한국어'
}
dir_list = ['train', 'val', 'test']

dir_count = {'train': 0, 'val': 0, 'test': 0}
word_count = {}
for eng, kor in word_dict.items():
    word_count[kor] = dir_count.copy()




data_dir = '/home/PHR/Lipreading_using_TCN_running/hangeul'
for word in word_list:
    for dir in dir_list:
        dir_path = f'{data_dir}/{word}/{dir}'
        for file in os.listdir(dir_path):
            if re.compile('[가-힣]+').findall(file) and file.endswith('.avi'):
                file_name, nums_ext = file.split('_')
                word_count[file_name][dir] += 1

word_count


{'특히': {'train': 30, 'val': 3, 'test': 2},
 '하지만': {'train': 38, 'val': 4, 'test': 4},
 '그리고': {'train': 32, 'val': 3, 'test': 3},
 '이렇게': {'train': 18, 'val': 3, 'test': 2},
 '함께': {'train': 28, 'val': 3, 'test': 3},
 '어떤': {'train': 28, 'val': 3, 'test': 3},
 '이번': {'train': 26, 'val': 3, 'test': 3},
 '오늘': {'train': 26, 'val': 3, 'test': 2},
 '다른': {'train': 30, 'val': 3, 'test': 3},
 '코로나': {'train': 16, 'val': 2, 'test': 2},
 '확진자': {'train': 26, 'val': 3, 'test': 3},
 '뉴스에서': {'train': 38, 'val': 3, 'test': 2},
 '미국': {'train': 20, 'val': 3, 'test': 3},
 '한국': {'train': 14, 'val': 2, 'test': 2},
 '한국어': {'train': 16, 'val': 2, 'test': 2}}

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt



In [87]:
import numpy as np

a = [(128,160),(170,166)]
a = np.array(a)
b = [(10,5),(10,5)]
b = np.array(b)
print(a)
print()
print(b)
print()
print(a/b)
print()
print()

[[128 160]
 [170 166]]

[[10  5]
 [10  5]]

[[12.8 32. ]
 [17.  33.2]]


